name: yc-job-getter

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check if should run
      id: check_run
      run: |
        RANDOM_NUMBER=$((RANDOM % 100 + 1))
        TARGET_NUMBER=$(shuf -i 1-100 -n 1)
        echo "RANDOM_NUMBER=$RANDOM_NUMBER" >> $GITHUB_ENV
        echo "TARGET_NUMBER=$TARGET_NUMBER" >> $GITHUB_ENV
        if [ "$RANDOM_NUMBER" -ne "$TARGET_NUMBER" ]; then
          echo "This run is skipped."
          exit 0

    - name: Trick Garry for $$$
      if: steps.check_run.outputs.TARGET_NUMBER == steps.check_run.outputs.RANDOM_NUMBER
      run: |
        echo " " >> README.md
        git config user.name "amrragab8080"
        git config user.email "informaticsdev@gmail.com"
        git add .
        git commit -m "Always green!"
        git push

    - name: Push changes
      if: steps.check_run.outputs.TARGET_NUMBER == steps.check_run.outputs.RANDOM_NUMBER
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        git push https://amrragab8080:${{ secrets.ACTIONS_PAT }}@github.com/amrragab8080/myego.git
