name: add-noise

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every minute
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check if should run
      id: check_run
      run: |
        RANDOM_NUMBER=$(shuf -i 1-100 -n 1)
        TARGET_NUMBER=$(shuf -i 1-100 -n 1)
        echo "RANDOM_NUMBER=$RANDOM_NUMBER" >> $GITHUB_ENV
        echo "TARGET_NUMBER=$TARGET_NUMBER" >> $GITHUB_ENV
        echo "random is: $RANDOM_NUMBER"
        echo "target is: $TARGET_NUMBER"
        if [ $(expr $RANDOM_NUMBER) -gt $(expr $TARGET_NUMBER) ]; then
          echo "This run is skipped."
          echo "run=true" >> $GITHUB_ENV
        else
          echo "run=false" >> $GITHUB_ENV
        fi

    - name: add noise
      if: env.run == 'true'
      run: |
        echo " " >> README.md
        git config user.name "amrragab8080"
        git config user.email "informaticsdev@gmail.com"
        git add .
        git commit -m "Random green for fun!"
      env:
        GITHUB_ENV: $GITHUB_ENV

    - name: Push changes
      if: env.run =='true'
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        GITHUB_ENV: $GITHUB_ENV
      run: |
        git push https://amrragab8080:${{ secrets.ACTIONS_PAT }}@github.com/amrragab8080/myego.git
